### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by Hisoka6602** [badcel/HidApi.Net#100]
System.DllNotFoundException:“Could not find hidapi library tried: hidapi.dll, libhidapi-0.dll”

V1.0.4

**Comment by badcel** [comment]
Please specify which operating system you are using and where the native HidApi binary is located as it is not part of the nuget package.

If you did not install HidApi on the machine with the exception please install it in a way that it is available to your program.

**Comment by badcel** [comment]
Closed because of missing information.
