### ISSUE TITLE
Provide a generic example like hidapi hidtest

### ISSUE THREAD

**Issue by mcuee** [badcel/HidApi.Net#33]
It would be good to provide a generic example like the hidapi project hidtest utility. You can ignore the test device portion (0x04d8:0x003f).
https://github.com/libusb/hidapi/blob/master/hidtest/test.c

**Comment by mcuee** [comment]
I think it would be good for testing of HidApi.Net. For example, you can check if the output is similar to the hidtest and if the C APIs have been implemented in HidApi.Net.

You will be supprised that many issues are discovered using the hidtest utility for the hidapi project. Quite some new features (pull requests) are also being tested using hidtest.

**Comment by badcel** [comment]
Did I miss something?

For me it looked like the tool is just printing some standard data like manufacturer or product. Then it is sending some arbitrary data to toggle some led according to the comments which sounds at least confusing (what if there is no led)?

Part of the code you linked is used in the HidApi readme there they state:

> Warning: Only run the code you understand, and only when it conforms to the device spec. Writing data (hid_write) at random to your HID devices can break them.

And they state:

>You can also use [hidtest/test.c](https://github.com/libusb/hidapi/blob/master/hidtest/test.c) as a starting point for your applications.

From this point of view it makes even less sense to implement it as it sounds dangerous for a user to execute. A starting template is already on the readme. I think it is okay to not send arbitrary data to an unknown device or have an easy way to execute the code as the user risks breaking their devices. If you use the library you should know what you are doing and I don’t want to put a big warning in capital letters onto the readme.

If you actually mean to create https://github.com/todbot/hidapitester I would understand your request but such a tool would probably better suited in a separate repo as I want to keep this repo small and simple.

**Comment by mcuee** [comment]
I think you have a point. It is okay to close this issue.

I am more based on my expeirences as an HIDAPI tester.

**Comment by mcuee** [comment]
BTW, you can ignore the test device used in hidtest, it is for a specific test device (0x04d8:0x003f).

**Comment by badcel** [comment]
I did not take detailed look but then it is just enumerating and printing standard data right (function `print_device`)?

For me it is okay to add the same code to this project's readme. PR is welcome. 👍

**Comment by mcuee** [comment]
I am not a programmer myself so I do not code myself. Rather my involvement on opensource projects (libusb, hidapi, libusb-win32, libusbK, avrdude, pyusb, libusbdotnet, etec), concentrates on testing and technical support.

But I will play with HidApi.Net to see if I find anything missing.

**Comment by badcel** [comment]
Thank you 😊
