### ISSUE TITLE
Error: Could not find hidapi library tried: hidapi.dll, libhidapi-0.dll

### ISSUE THREAD

**Issue by Ovinov84** [badcel/HidApi.Net#49]
what to do?

**Comment by badcel** [comment]
Like mentioned in the readme you are responsible to distribute the HidApi c library yourself as part of your app as it is not part of the nuget.

This usually means copying the hidapi DLL alongside your executable.

You can get the file for example from the official project: https://github.com/libusb/hidapi/releases/tag/hidapi-0.14.0

**Comment by badcel** [comment]
If this does not fix your problem feel free to reach out again.
