### ISSUE TITLE
Provide support for a NET Standard 2.0

### ISSUE THREAD

**Issue by alextnull** [badcel/HidApi.Net#82]
Provide support for a NET Standard 2.0

**Comment by badcel** [comment]
Hi, I'm not sure if this will ever happen as I want to keep the code simple and modern.

So for example if dotnet 6 goes out of support it will probably be dropped, too. (There is already duplicated code to keep support for dotnet 6. Supporting net standard would probably increase this even more.)

If you need support for dotnet framework I think there are other nuget packages available.

**Comment by badcel** [comment]
So my recommendation in this case is to multi target your app / library and conditionally reference different nuget packages. Then create some abstraction layer which supports both packages and allows your app to use whichever binding is available.

This separates your dependencies cleanly from your core logic which should be desired anyway.

**Comment by alextnull** [comment]
OK, I decided to go with fork for now.
